---
title: "LDCT"
output:
  pdf_document: default
  html_document: default
  word_document: default
date: '2022-12-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load data
```{r}
#setwd("~/Documents/TDP control files/Longitudinal induction analysis/EPM/")
# Loading
library(pacman)
p_load(readxl, tidyverse)
# xlsx files
df <- read_excel("EPM_binned_longitudinal_data.xlsx")


```


Time spent in dark chamber:
```{r}
#periphery_preference = time spent in periphery / time spent in center
 df<-  df %>% mutate(time_dark=df$`In zone Closed_arm1 cumulative`+df$`In zone Closed_arm2 cumulative`)
 df<-  df %>% mutate(time_light=df$`In zone Open_arm1 cumulative`+df$`In zone Open_arm2 cumaltive`)
# 
# #relative time spent in dark over light
 df<-  df %>% mutate(light_preference=time_light/(time_light+time_dark)*100) 


```

Frequency in arms
```{r}
#frequency in dark and light arms
df<-  df %>% mutate(freq_dark=df$`In zone Closed_arm1  frequency`+df$`In zone Closed_arm2 frequency`)
df<-  df %>% mutate(freq_light=df$`In zone Open_arm1 frequency`+df$`In zone Open_arm2 frequency`)

#relative time spent in dark over light as entries in open arm / total arm entries
df<-  df %>% mutate(light_preference_freq=freq_light/(freq_light+freq_dark)*100) 

```


Data set where participants not completing all data collection time points are sorted out

```{r}
# Determine the weeks each participant should have
required_weeks <- df %>% 
  distinct(Week) %>% 
  pull()

# Count the number of weeks each participant has data for
participant_week_counts <- df %>%
  group_by(ID) %>%
  summarize(week_count = n_distinct(Week))

# Identify participants with data for all required weeks
complete_participants <- participant_week_counts %>%
  filter(week_count == length(required_weeks)) %>%
  pull(ID)

# Filter the dataset to include only complete participants
df_complete <- df %>%
  filter(ID %in% complete_participants)

# View the new dataset
head(df_complete)
```

```{r}

df$Week <- factor(df$Week , levels = c("Preinduction","1st week post induction","2nd week post induction"))


model <- lmer(light_preference ~ Week*Timebin + (1 | ID), data = df)
#Compare First vs. Last 5 Minutes within Each Week
emmeans(model, pairwise ~ Timebin | Week, adjust = "bonferroni")

#Compare Distance Moved Across Weeks for Each Trial Period
emmeans(model, pairwise ~ Week | Timebin, adjust = "bonferroni")

#plot(emmeans(model, ~ Week * Timebin))

```

```{r}
#p_load(performance)
check_model(model)
```

```{r}
# Ensure 'Week' and 'timebin' are factors with appropriate levels

df$Timebin <- as.factor(df$Timebin)
class(df$Timebin)
#df$Timebin <- factor(df$Timebin, levels = c("Timebin 1", "Timebin 2"))

# Load required packages
p_load(ggbeeswarm, ggsignif)

# Create the plot
ggplot(df, aes(x = interaction(Week, Timebin), y = light_preference)) +
  geom_beeswarm(size = 2.5, aes(color = ID)) +
  ylab("Light preference") +
  xlab("Timepoint") +
  
  # Add significance comparisons
  geom_signif(comparisons = list(c("Preinduction.Timebin 1", "1st week post induction.Timebin 1")),
              map_signif_level = TRUE,
              y_position = 30,
              annotations = c("0.0146")) +
  geom_signif(comparisons = list(c("Preinduction.Timebin 1", "2nd week post induction.Timebin 1")),
              map_signif_level = TRUE,
              y_position = 40,
              annotations = c("0.4282")) +
  geom_signif(comparisons = list(c("1st week post induction.Timebin 1", "2nd week post induction.Timebin 1")),
              map_signif_level = TRUE,
              y_position = 50,
              annotations = c("0.7723")) +
  
    geom_signif(comparisons = list(c("Preinduction.Timebin 2", "1st week post induction.Timebin 2")),
              map_signif_level = TRUE,
              y_position = 30,
              annotations = c("1.0000")) +
  geom_signif(comparisons = list(c("Preinduction.Timebin 2", "2nd week post induction.Timebin 2")),
              map_signif_level = TRUE,
              y_position = 40,
              annotations = c("0.0655")) +
  geom_signif(comparisons = list(c("1st week post induction.Timebin 2", "2nd week post induction.Timebin 2")),
              map_signif_level = TRUE,
              y_position = 50,
              annotations = c("0.0318")) +

  # Add mean and error bars
  geom_crossbar(stat = "summary", fun = mean, width = 0.2, fatten = 1.5) +
  geom_errorbar(stat = "summary", fun.data = mean_se, width = 0.1, position = position_dodge(width = 0.75)) +
  
  # Improve theme
  theme(text = element_text(size = 13),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, 55)
```


```{r}
# Ensure 'Week' and 'Timebin' are factors
df$Week <- factor(df$Week, levels = c("Preinduction", "1st week post induction", "2nd week post induction"))
df$Timebin <- factor(df$Timebin, levels = c("Timebin 1", "Timebin 2"))

# Load required packages
p_load(ggbeeswarm, ggsignif)

# Create the plot
ggplot(df, aes(x = interaction(Timebin, Week, sep = " "), y = light_preference)) +
  geom_beeswarm(size = 2.5, aes(color = ID)) +
  ylab("Light preference") +
  xlab("Timepoint") +
  
  # Add significance comparisons
  geom_signif(comparisons = list(c("Timebin 1 Preinduction", "Timebin 2 Preinduction")),
              map_signif_level = TRUE,
              y_position = 30,
              annotations = c("0.0259")) +
  geom_signif(comparisons = list(c("Timebin 1 1st week post induction", "Timebin 2 1st week post induction")),
              map_signif_level = TRUE,
              y_position = 40,
              annotations = c("0.7341")) +
  geom_signif(comparisons = list(c("Timebin 1 2nd week post induction", "Timebin 2 2nd week post induction")),
              map_signif_level = TRUE,
              y_position = 50,
              annotations = c("0.0953")) +
  
  # Add mean and error bars
  geom_crossbar(stat = "summary", fun = mean, width = 0.2, fatten = 1.5, position = position_dodge(width = 0.75)) +
  geom_errorbar(stat = "summary", fun.data = mean_se, width = 0.1, position = position_dodge(width = 0.75)) +
  
  # Improve theme
  theme(text = element_text(size = 13),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
    ylim(0, 55)
```